version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo INSTALL started on `date`
            - npm install
    build:
        commands:
            - echo Building bundles started on `date`
            - npm run build
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: dist